<a href="https://colab.research.google.com/github/Malu247/programacion1-/blob/main/modulospdynp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Modulos integrados

In [1]:
import numpy as np

In [15]:
a = np.array([1,2,3,4])
b = np.array([[1,2], [3,4], [1,5]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [1 5]]

In [16]:
lista = [1,2,3]
arr = np.array([1,2,3]) #Arreglos de numpy se interpretan matematicamente

In [17]:
lista*2 #La lista concatenada dos veces

[1, 2, 3, 1, 2, 3]

In [18]:
arr*2

array([2, 4, 6])

In [19]:
arr.shape

(3,)

In [20]:
b.shape #Arreglo de 3 componentes con 2 elementos

(3, 2)

In [21]:
arr.ndim #Numero de elementos por componentes

1

In [22]:
b.ndim

2

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.arange(0, 10, 2) #Va desde 0 hasta el anterior a 10, separados de a 2

array([0, 2, 4, 6, 8])

In [30]:
arry = np.linspace(0,20,5)
arry #5 elementos equidistantes de 0 a 20

array([ 0.,  5., 10., 15., 20.])

In [31]:
arry[0:2] #Toma del 0 al antes del indice 2

array([0., 5.])

In [32]:
matrix = np.array([[1,2], [3,4], [1,5]])

In [33]:
matrix[0,1] #El indice 1 de la 0-esima fila

np.int64(2)

In [34]:
matrix[:,1] #Los elemntos de la 1 columna

array([2, 4, 5])

In [35]:
matrix[1,:] #Los elementos de la 1 fila

array([3, 4])

In [36]:
b + matrix

array([[ 2,  4],
       [ 6,  8],
       [ 2, 10]])

In [37]:
b*matrix #producto de hadamard (componente a componenete)

array([[ 1,  4],
       [ 9, 16],
       [ 1, 25]])

In [38]:
c = np.array([1.65, 1.54, 1.70, 1.44, 1.69, 1.80])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

1.6366666666666667 1.67 0.11671427600007732 9.82 1.44 1.8

Manipulacion de arreglos

In [39]:
d = np.array([1,2,3,4,5,6])
d.reshape(2,3) #Arreglo con filas y columas dadas

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
matrix.reshape(2,3)

array([[1, 2, 3],
       [4, 1, 5]])

In [44]:
np.concatenate([d,d])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [46]:
d.flatten() #vectoriza (aplana) la matriz

array([1, 2, 3, 4, 5, 6])

In [48]:
f = np.array(([1,2], [3,4]))
h = np.array(([8,2], [3,5]))
np.dot(f,h) #multiplica las matrices

array([[14, 12],
       [36, 26]])

In [50]:
np.linalg.inv(f)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [51]:
np.random.rand(10) #Genera 10 valores de una distribucion uniforme entre (0,1)

array([0.54413779, 0.94953504, 0.65790825, 0.62749818, 0.57963405,
       0.28366963, 0.34280954, 0.03399534, 0.98525458, 0.80428718])

In [52]:
np.random.randint(0,5) #valor entero random entre 0 y el anterior a 5

3

In [53]:
np.random.randn(8) #valores aleatorios de una distribucion normal con media 0 y desviacion estandar 1

array([-0.73837584, -0.24025867, -0.1972503 , -0.01319472, -0.16702539,
        0.49777879,  0.70550886, -0.84967693])

In [55]:
u = h[h > 3]
u

array([8, 5])

In [57]:
np.where(h>3, 1, 0) #Los mayores a 3 pone 1 y los que no pone 0

array([[1, 0],
       [0, 1]])

In [58]:
np.where(h>3, 1, h) #Deja los que no igual

array([[1, 2],
       [3, 1]])

Ejercicio

In [61]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
b = a*5
b

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [63]:
a[a>5]

array([ 6,  7,  8,  9, 10])

In [67]:
c = np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
print(np.mean(a))
print(np.std(a))

5.5
2.8722813232690143

In [69]:
k = np.where(a>7,1,a)
k

array([1, 2, 3, 4, 5, 6, 7, 1, 1, 1])

In [70]:
import pandas as pd

In [72]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1500, 2000, 3000, 2500]
}) # creando data.frames
df

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [73]:
df.head(2)

  nombre    ciudad  edad  salario
0    Ana    Bogotá    23     1500
1   Luis  Medellín    30     2000

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [75]:
df.describe()

            edad      salario
count   4.000000     4.000000
mean   29.000000  2250.000000
std     4.966555   645.497224
min    23.000000  1500.000000
25%    26.750000  1875.000000
50%    29.000000  2250.000000
75%    31.250000  2625.000000
max    35.000000  3000.000000

In [77]:
df.shape #numero de filas y columnas

(4, 4)

In [78]:
df["edad"]

0    23
1    30
2    35
3    28
Name: edad, dtype: int64

In [82]:
df[(df["edad"]>20) & (df["edad"]<40)]

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [83]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
    'edad': [23, np.nan, 35, 23, 40],
    'salario': [1000, 2000, None, 1000, 5000],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
}
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
 'edad': [23, nan, 35, 23, 40],
 'salario': [1000, 2000, None, 1000, 5000],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']}

In [87]:
data = pd.DataFrame(data)
data

   nombre  edad  salario    ciudad
0     Ana  23.0   1000.0    Bogotá
1    Luis   NaN   2000.0  Medellín
2  Carlos  35.0      NaN      Cali
3     Ana  23.0   1000.0    Bogotá
4    None  40.0   5000.0      Cali

In [89]:
data.isnull().sum() #1 si falta valor, 0 si no falta ninguno

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

In [90]:
data2 = data.dropna() #elimina las filas que tengan valores faltantes
data2

  nombre  edad  salario  ciudad
0    Ana  23.0   1000.0  Bogotá
3    Ana  23.0   1000.0  Bogotá

In [92]:
data3 = data.dropna(subset=["salario"]) #solo se eliminan las filas de la columna escrita
data3

  nombre  edad  salario    ciudad
0    Ana  23.0   1000.0    Bogotá
1   Luis   NaN   2000.0  Medellín
3    Ana  23.0   1000.0    Bogotá
4   None  40.0   5000.0      Cali

In [94]:
data["edad"] = data["edad"].fillna(data["edad"].mean()) #En la columna edad, remplace los valores nulos por la media aritmetica de los valores de edad
data["nombre"] = data["nombre"].fillna("descoocido")
data

       nombre   edad  salario    ciudad
0         Ana  23.00   1000.0    Bogotá
1        Luis  30.25   2000.0  Medellín
2      Carlos  35.00      NaN      Cali
3         Ana  23.00   1000.0    Bogotá
4  descoocido  40.00   5000.0      Cali

In [95]:
data["ciudad"] = data["ciudad"].replace("Bogotá", "BOGOTA")
data

       nombre   edad  salario    ciudad
0         Ana  23.00   1000.0    BOGOTA
1        Luis  30.25   2000.0  Medellín
2      Carlos  35.00      NaN      Cali
3         Ana  23.00   1000.0    BOGOTA
4  descoocido  40.00   5000.0      Cali

In [101]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': [' Ana', 'LUIS ', 'Carlos', 'ana'],
    'edad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín']
})
dfn

   id  nombre  edad  salario    ciudad
0   1     Ana    23     1000    Bogotá
1   2   LUIS     30     2000      Cali
2   3  Carlos    35     3000    Bogotá
3   4     ana    28     1500  Medellín

In [102]:
dfn["salario_anual"] = dfn["salario"] * 12
dfn["edad_doble"] = dfn["edad"].apply(lambda x:x*2)
dfn

   id  nombre  edad  salario    ciudad  salario_anual  edad_doble
0   1     Ana    23     1000    Bogotá          12000          46
1   2   LUIS     30     2000      Cali          24000          60
2   3  Carlos    35     3000    Bogotá          36000          70
3   4     ana    28     1500  Medellín          18000          56

In [103]:
dfn = dfn.rename(columns={"edad":"age"})
dfn

   id  nombre  age  salario    ciudad  salario_anual  edad_doble
0   1     Ana   23     1000    Bogotá          12000          46
1   2   LUIS    30     2000      Cali          24000          60
2   3  Carlos   35     3000    Bogotá          36000          70
3   4     ana   28     1500  Medellín          18000          56

In [106]:
grupo = dfn.groupby("ciudad")["salario"].mean()
grupo

ciudad
Bogotá      2000.0
Cali        2000.0
Medellín    1500.0
Name: salario, dtype: float64

In [108]:
ordenado = dfn.sort_values(by="age")
ordenado

   id  nombre  age  salario    ciudad  salario_anual  edad_doble
0   1     Ana   23     1000    Bogotá          12000          46
3   4     ana   28     1500  Medellín          18000          56
1   2   LUIS    30     2000      Cali          24000          60
2   3  Carlos   35     3000    Bogotá          36000          70

In [109]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'Marketing']
})
dfn1

   id departamento
0   1       Ventas
1   2           IT
2   3         RRHH
3   4    Marketing

In [110]:
valores = dfn.values
valores

array([[1, ' Ana', 23, 1000, 'Bogotá', 12000, 46],
       [2, 'LUIS ', 30, 2000, 'Cali', 24000, 60],
       [3, 'Carlos', 35, 3000, 'Bogotá', 36000, 70],
       [4, 'ana', 28, 1500, 'Medellín', 18000, 56]], dtype=object)

In [111]:
dg = pd.DataFrame(valores)
dg

   0       1   2     3         4      5   6
0  1     Ana  23  1000    Bogotá  12000  46
1  2   LUIS   30  2000      Cali  24000  60
2  3  Carlos  35  3000    Bogotá  36000  70
3  4     ana  28  1500  Medellín  18000  56